services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  test-db:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-data:/data/test-db
